import images from './images';

export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number;
  image: any;
  collection?: string;
  collectionImages?: any[];
  brandLogo?: any;
  isCollectionItem?: boolean;
}

export const products: Product[] = [
  {
    id: 'jumpsuit_2',
    name: 'Jumpsuit Collection Item 2',
    brand: 'Lilith',
    price: 4200,
    image: require('../assets/images/lilith/jumpsuit collection/summer_2.jpg'),
    collection: 'Jumpsuit Collection',
    collectionImages: [
      require('../assets/images/lilith/jumpsuit collection/summer.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_2.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_3.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_4.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_5.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_6.jpg'),
    ],
    brandLogo: require('../assets/images/lilith/lilith_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'abc_1',
    name: 'ABC Collection Item 1',
    brand: 'Sleek',
    price: 4200,
    image: require('../assets/images/sleek/ABC Collection/ABC.jpg'),
    collection: 'ABC Collection',
    collectionImages: [
      require('../assets/images/sleek/ABC Collection/ABC.jpg'),
      require('../assets/images/sleek/ABC Collection/ABC_2.jpg'),
      require('../assets/images/sleek/ABC Collection/ABC_3.jpg'),
    ],
    brandLogo: require('../assets/images/sleek/sleek_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'jumpsuit_3',
    name: 'Jumpsuit Collection Item 3',
    brand: 'Lilith',
    price: 4200,
    image: require('../assets/images/lilith/jumpsuit collection/summer_3.jpg'),
    collection: 'Jumpsuit Collection',
    collectionImages: [
      require('../assets/images/lilith/jumpsuit collection/summer.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_2.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_3.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_4.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_5.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_6.jpg'),
    ],
    brandLogo: require('../assets/images/lilith/lilith_logo.jpg'),
    isCollectionItem: true,
  },
  // Sleek Products - ABC Collection
  {
    id: 'abc_2',
    name: 'ABC Collection Item 2',
    brand: 'Sleek',
    price: 4200,
    image: require('../assets/images/sleek/ABC Collection/ABC_2.jpg'),
    collection: 'ABC Collection',
    collectionImages: [
      require('../assets/images/sleek/ABC Collection/ABC.jpg'),
      require('../assets/images/sleek/ABC Collection/ABC_2.jpg'),
      require('../assets/images/sleek/ABC Collection/ABC_3.jpg'),
    ],
    brandLogo: require('../assets/images/sleek/sleek_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'abc_3',
    name: 'ABC Collection Item 3',
    brand: 'Sleek',
    price: 4200,
    image: require('../assets/images/sleek/ABC Collection/ABC_3.jpg'),
    collection: 'ABC Collection',
    collectionImages: [
      require('../assets/images/sleek/ABC Collection/ABC.jpg'),
      require('../assets/images/sleek/ABC Collection/ABC_2.jpg'),
      require('../assets/images/sleek/ABC Collection/ABC_3.jpg'),
    ],
    brandLogo: require('../assets/images/sleek/sleek_logo.jpg'),
    isCollectionItem: true,
  },

  // Sleek Products - FW24 Collection
  {
    id: 'fw24_1',
    name: 'FW24 Jacket 1',
    brand: 'Sleek',
    price: 5500,
    image: require('../assets/images/sleek/FW24 Collection/Jacket.jpg'),
    collection: 'FW24 Collection',
    collectionImages: [
      require('../assets/images/sleek/FW24 Collection/Jacket.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_2.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_3.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_4.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_5.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_6.jpg'),
    ],
    brandLogo: require('../assets/images/sleek/sleek_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'fw24_2',
    name: 'FW24 Jacket 2',
    brand: 'Sleek',
    price: 5500,
    image: require('../assets/images/sleek/FW24 Collection/Jacket_2.jpg'),
    collection: 'FW24 Collection',
    collectionImages: [
      require('../assets/images/sleek/FW24 Collection/Jacket.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_2.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_3.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_4.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_5.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_6.jpg'),
    ],
    brandLogo: require('../assets/images/sleek/sleek_logo.jpg'),
    isCollectionItem: true,
  },
  // Add remaining FW24 items (3-6)...

  // Sleek Products - FW24 Collection (continued)
  {
    id: 'fw24_3',
    name: 'FW24 Jacket 3',
    brand: 'Sleek',
    price: 5500,
    image: require('../assets/images/sleek/FW24 Collection/Jacket_3.jpg'),
    collection: 'FW24 Collection',
    collectionImages: [
      require('../assets/images/sleek/FW24 Collection/Jacket.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_2.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_3.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_4.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_5.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_6.jpg'),
    ],
    brandLogo: require('../assets/images/sleek/sleek_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'fw24_4',
    name: 'FW24 Jacket 4',
    brand: 'Sleek',
    price: 5500,
    image: require('../assets/images/sleek/FW24 Collection/Jacket_4.jpg'),
    collection: 'FW24 Collection',
    collectionImages: [
      require('../assets/images/sleek/FW24 Collection/Jacket.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_2.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_3.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_4.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_5.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_6.jpg'),
    ],
    brandLogo: require('../assets/images/sleek/sleek_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'fw24_5',
    name: 'FW24 Jacket 5',
    brand: 'Sleek',
    price: 5500,
    image: require('../assets/images/sleek/FW24 Collection/Jacket_5.jpg'),
    collection: 'FW24 Collection',
    collectionImages: [
      require('../assets/images/sleek/FW24 Collection/Jacket.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_2.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_3.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_4.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_5.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_6.jpg'),
    ],
    brandLogo: require('../assets/images/sleek/sleek_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'fw24_6',
    name: 'FW24 Jacket 6',
    brand: 'Sleek',
    price: 5500,
    image: require('../assets/images/sleek/FW24 Collection/Jacket_6.jpg'),
    collection: 'FW24 Collection',
    collectionImages: [
      require('../assets/images/sleek/FW24 Collection/Jacket.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_2.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_3.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_4.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_5.jpg'),
      require('../assets/images/sleek/FW24 Collection/Jacket_6.jpg'),
    ],
    brandLogo: require('../assets/images/sleek/sleek_logo.jpg'),
    isCollectionItem: true,
  },

  // Sleek Products - FW23 Collection
  {
    id: 'fw23_1',
    name: 'FW23 Black Edition 1',
    brand: 'Sleek',
    price: 4800,
    image: require('../assets/images/sleek/FW23 Collection/Black.jpg'),
    collection: 'FW23 Collection',
    collectionImages: [
      require('../assets/images/sleek/FW23 Collection/Black.jpg'),
      require('../assets/images/sleek/FW23 Collection/Black_2.jpg'),
      require('../assets/images/sleek/FW23 Collection/Black_3.jpg'),
    ],
    brandLogo: require('../assets/images/sleek/sleek_logo.jpg'),
    isCollectionItem: true,
  },
  // Add remaining FW23 items (2-3)...

  // Sleek Products - FW23 Collection (continued)
  {
    id: 'fw23_2',
    name: 'FW23 Black Edition 2',
    brand: 'Sleek',
    price: 4800,
    image: require('../assets/images/sleek/FW23 Collection/Black_2.jpg'),
    collection: 'FW23 Collection',
    collectionImages: [
      require('../assets/images/sleek/FW23 Collection/Black.jpg'),
      require('../assets/images/sleek/FW23 Collection/Black_2.jpg'),
      require('../assets/images/sleek/FW23 Collection/Black_3.jpg'),
    ],
    brandLogo: require('../assets/images/sleek/sleek_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'fw23_3',
    name: 'FW23 Black Edition 3',
    brand: 'Sleek',
    price: 4800,
    image: require('../assets/images/sleek/FW23 Collection/Black_3.jpg'),
    collection: 'FW23 Collection',
    collectionImages: [
      require('../assets/images/sleek/FW23 Collection/Black.jpg'),
      require('../assets/images/sleek/FW23 Collection/Black_2.jpg'),
      require('../assets/images/sleek/FW23 Collection/Black_3.jpg'),
    ],
    brandLogo: require('../assets/images/sleek/sleek_logo.jpg'),
    isCollectionItem: true,
  },

  // Undyingbrand - Classic Polo Shirt Collection
  {
    id: 'classic_polo_1',
    name: 'Classic Polo 1',
    brand: 'Undyingbrand',
    price: 2200,
    image: require('../assets/images/undyingbrand/classic polo shirt/polo.jpg'),
    collection: 'Classic Polo Collection',
    collectionImages: [
      require('../assets/images/undyingbrand/classic polo shirt/polo.jpg'),
      require('../assets/images/undyingbrand/classic polo shirt/polo_1.jpg'),
    ],
    brandLogo: require('../assets/images/undyingbrand/undyingbrand_logo.jpg'),
    isCollectionItem: true,
  },
  // Add remaining Classic Polo items...

  // Undyingbrand - Classic Polo Shirt Collection (continued)
  {
    id: 'classic_polo_2',
    name: 'Classic Polo 2',
    brand: 'Undyingbrand',
    price: 2200,
    image: require('../assets/images/undyingbrand/classic polo shirt/polo_1.jpg'),
    collection: 'Classic Polo Collection',
    collectionImages: [
      require('../assets/images/undyingbrand/classic polo shirt/polo.jpg'),
      require('../assets/images/undyingbrand/classic polo shirt/polo_1.jpg'),
    ],
    brandLogo: require('../assets/images/undyingbrand/undyingbrand_logo.jpg'),
    isCollectionItem: true,
  },

  // Undyingbrand - Dapper Polo Shirt Collection
  {
    id: 'dapper_polo_1',
    name: 'Dapper Polo 1',
    brand: 'Undyingbrand',
    price: 2500,
    image: require('../assets/images/undyingbrand/dapper polo shirt/polo.jpg'),
    collection: 'Dapper Polo Collection',
    collectionImages: [
      require('../assets/images/undyingbrand/dapper polo shirt/polo.jpg'),
      require('../assets/images/undyingbrand/dapper polo shirt/polo_2.jpg'),
    ],
    brandLogo: require('../assets/images/undyingbrand/undyingbrand_logo.jpg'),
    isCollectionItem: true,
  },
  // Add remaining Dapper Polo items...

  // Undyingbrand - Dapper Polo Shirt Collection (continued)
  {
    id: 'dapper_polo_2',
    name: 'Dapper Polo 2',
    brand: 'Undyingbrand',
    price: 2500,
    image: require('../assets/images/undyingbrand/dapper polo shirt/polo_2.jpg'),
    collection: 'Dapper Polo Collection',
    collectionImages: [
      require('../assets/images/undyingbrand/dapper polo shirt/polo.jpg'),
      require('../assets/images/undyingbrand/dapper polo shirt/polo_2.jpg'),
    ],
    brandLogo: require('../assets/images/undyingbrand/undyingbrand_logo.jpg'),
    isCollectionItem: true,
  },

  // Defclo - Mermaid Collection
  {
    id: 'mermaid_1',
    name: 'Mermaid Green Sequin Top 1',
    brand: 'Defclo',
    price: 3200,
    image: require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework.jpg'),
    collection: 'Mermaid Collection',
    collectionImages: [
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_2.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_3.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_4.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_5.jpg'),
    ],
    brandLogo: require('../assets/images/defclo/defclo_logo.jpg'),
    isCollectionItem: true,
  },
  // Add remaining Mermaid items...

  // Defclo - Mermaid Collection (continued)
  {
    id: 'mermaid_2',
    name: 'Mermaid Green Sequin Top 2',
    brand: 'Defclo',
    price: 3200,
    image: require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_2.jpg'),
    collection: 'Mermaid Collection',
    collectionImages: [
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_2.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_3.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_4.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_5.jpg'),
    ],
    brandLogo: require('../assets/images/defclo/defclo_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'mermaid_3',
    name: 'Mermaid Green Sequin Top 3',
    brand: 'Defclo',
    price: 3200,
    image: require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_3.jpg'),
    collection: 'Mermaid Collection',
    collectionImages: [
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_2.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_3.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_4.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_5.jpg'),
    ],
    brandLogo: require('../assets/images/defclo/defclo_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'mermaid_4',
    name: 'Mermaid Green Sequin Top 4',
    brand: 'Defclo',
    price: 3200,
    image: require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_4.jpg'),
    collection: 'Mermaid Collection',
    collectionImages: [
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_2.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_3.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_4.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_5.jpg'),
    ],
    brandLogo: require('../assets/images/defclo/defclo_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'mermaid_5',
    name: 'Mermaid Green Sequin Top 5',
    brand: 'Defclo',
    price: 3200,
    image: require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_5.jpg'),
    collection: 'Mermaid Collection',
    collectionImages: [
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_2.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_3.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_4.jpg'),
      require('../assets/images/defclo/Mermaid Green Thin Strap Cowl Neck Sequin Top/firework_5.jpg'),
    ],
    brandLogo: require('../assets/images/defclo/defclo_logo.jpg'),
    isCollectionItem: true,
  },

  // Defclo - Femme Collection
  {
    id: 'femme_1',
    name: 'Femme Collection Item 1',
    brand: 'Defclo',
    price: 2800,
    image: require('../assets/images/defclo/femme/jeon.jpg'),
    collection: 'Femme Collection',
    collectionImages: [
      require('../assets/images/defclo/femme/jeon.jpg'),
      require('../assets/images/defclo/femme/jeon_2.jpg'),
      require('../assets/images/defclo/femme/jeon_3.jpg'),
      require('../assets/images/defclo/femme/jeon_4.jpg'),
      require('../assets/images/defclo/femme/jeon_5.jpg'),
      require('../assets/images/defclo/femme/jeon_6.jpg'),
      require('../assets/images/defclo/femme/jeon_7.jpg'),
    ],
    brandLogo: require('../assets/images/defclo/defclo_logo.jpg'),
    isCollectionItem: true,
  },
  // Add remaining Femme items...

  // Defclo - Femme Collection (continued)
  {
    id: 'femme_2',
    name: 'Femme Collection Item 2',
    brand: 'Defclo',
    price: 2800,
    image: require('../assets/images/defclo/femme/jeon_2.jpg'),
    collection: 'Femme Collection',
    collectionImages: [
      require('../assets/images/defclo/femme/jeon.jpg'),
      require('../assets/images/defclo/femme/jeon_2.jpg'),
      require('../assets/images/defclo/femme/jeon_3.jpg'),
      require('../assets/images/defclo/femme/jeon_4.jpg'),
      require('../assets/images/defclo/femme/jeon_5.jpg'),
      require('../assets/images/defclo/femme/jeon_6.jpg'),
      require('../assets/images/defclo/femme/jeon_7.jpg'),
    ],
    brandLogo: require('../assets/images/defclo/defclo_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'femme_3',
    name: 'Femme Collection Item 3',
    brand: 'Defclo',
    price: 2800,
    image: require('../assets/images/defclo/femme/jeon_3.jpg'),
    collection: 'Femme Collection',
    collectionImages: [
      require('../assets/images/defclo/femme/jeon.jpg'),
      require('../assets/images/defclo/femme/jeon_2.jpg'),
      require('../assets/images/defclo/femme/jeon_3.jpg'),
      require('../assets/images/defclo/femme/jeon_4.jpg'),
      require('../assets/images/defclo/femme/jeon_5.jpg'),
      require('../assets/images/defclo/femme/jeon_6.jpg'),
      require('../assets/images/defclo/femme/jeon_7.jpg'),
    ],
    brandLogo: require('../assets/images/defclo/defclo_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'femme_4',
    name: 'Femme Collection Item 4',
    brand: 'Defclo',
    price: 2800,
    image: require('../assets/images/defclo/femme/jeon_4.jpg'),
    collection: 'Femme Collection',
    collectionImages: [
      require('../assets/images/defclo/femme/jeon.jpg'),
      require('../assets/images/defclo/femme/jeon_2.jpg'),
      require('../assets/images/defclo/femme/jeon_3.jpg'),
      require('../assets/images/defclo/femme/jeon_4.jpg'),
      require('../assets/images/defclo/femme/jeon_5.jpg'),
      require('../assets/images/defclo/femme/jeon_6.jpg'),
      require('../assets/images/defclo/femme/jeon_7.jpg'),
    ],
    brandLogo: require('../assets/images/defclo/defclo_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'femme_5',
    name: 'Femme Collection Item 5',
    brand: 'Defclo',
    price: 2800,
    image: require('../assets/images/defclo/femme/jeon_5.jpg'),
    collection: 'Femme Collection',
    collectionImages: [
      require('../assets/images/defclo/femme/jeon.jpg'),
      require('../assets/images/defclo/femme/jeon_2.jpg'),
      require('../assets/images/defclo/femme/jeon_3.jpg'),
      require('../assets/images/defclo/femme/jeon_4.jpg'),
      require('../assets/images/defclo/femme/jeon_5.jpg'),
      require('../assets/images/defclo/femme/jeon_6.jpg'),
      require('../assets/images/defclo/femme/jeon_7.jpg'),
    ],
    brandLogo: require('../assets/images/defclo/defclo_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'femme_6',
    name: 'Femme Collection Item 6',
    brand: 'Defclo',
    price: 2800,
    image: require('../assets/images/defclo/femme/jeon_6.jpg'),
    collection: 'Femme Collection',
    collectionImages: [
      require('../assets/images/defclo/femme/jeon.jpg'),
      require('../assets/images/defclo/femme/jeon_2.jpg'),
      require('../assets/images/defclo/femme/jeon_3.jpg'),
      require('../assets/images/defclo/femme/jeon_4.jpg'),
      require('../assets/images/defclo/femme/jeon_5.jpg'),
      require('../assets/images/defclo/femme/jeon_6.jpg'),
      require('../assets/images/defclo/femme/jeon_7.jpg'),
    ],
    brandLogo: require('../assets/images/defclo/defclo_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'femme_7',
    name: 'Femme Collection Item 7',
    brand: 'Defclo',
    price: 2800,
    image: require('../assets/images/defclo/femme/jeon_7.jpg'),
    collection: 'Femme Collection',
    collectionImages: [
      require('../assets/images/defclo/femme/jeon.jpg'),
      require('../assets/images/defclo/femme/jeon_2.jpg'),
      require('../assets/images/defclo/femme/jeon_3.jpg'),
      require('../assets/images/defclo/femme/jeon_4.jpg'),
      require('../assets/images/defclo/femme/jeon_5.jpg'),
      require('../assets/images/defclo/femme/jeon_6.jpg'),
      require('../assets/images/defclo/femme/jeon_7.jpg'),
    ],
    brandLogo: require('../assets/images/defclo/defclo_logo.jpg'),
    isCollectionItem: true,
  },

  // Lilith - Twin Set Collection
  {
    id: 'twinset_1',
    name: 'Twin Set Collection Item 1',
    brand: 'Lilith',
    price: 3500,
    image: require('../assets/images/lilith/Twin Set/unfazed.jpg'),
    collection: 'Twin Set Collection',
    collectionImages: [
      require('../assets/images/lilith/Twin Set/unfazed.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_2.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_3.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_4.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_5.jpg'),
    ],
    brandLogo: require('../assets/images/lilith/lilith_logo.jpg'),
    isCollectionItem: true,
  },
  // Add remaining Twin Set items...

  // Lilith - Twin Set Collection (continued)
  {
    id: 'twinset_2',
    name: 'Twin Set Collection Item 2',
    brand: 'Lilith',
    price: 3500,
    image: require('../assets/images/lilith/Twin Set/unfazed_2.jpg'),
    collection: 'Twin Set Collection',
    collectionImages: [
      require('../assets/images/lilith/Twin Set/unfazed.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_2.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_3.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_4.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_5.jpg'),
    ],
    brandLogo: require('../assets/images/lilith/lilith_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'twinset_3',
    name: 'Twin Set Collection Item 3',
    brand: 'Lilith',
    price: 3500,
    image: require('../assets/images/lilith/Twin Set/unfazed_3.jpg'),
    collection: 'Twin Set Collection',
    collectionImages: [
      require('../assets/images/lilith/Twin Set/unfazed.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_2.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_3.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_4.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_5.jpg'),
    ],
    brandLogo: require('../assets/images/lilith/lilith_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'twinset_4',
    name: 'Twin Set Collection Item 4',
    brand: 'Lilith',
    price: 3500,
    image: require('../assets/images/lilith/Twin Set/unfazed_4.jpg'),
    collection: 'Twin Set Collection',
    collectionImages: [
      require('../assets/images/lilith/Twin Set/unfazed.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_2.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_3.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_4.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_5.jpg'),
    ],
    brandLogo: require('../assets/images/lilith/lilith_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'twinset_5',
    name: 'Twin Set Collection Item 5',
    brand: 'Lilith',
    price: 3500,
    image: require('../assets/images/lilith/Twin Set/unfazed_5.jpg'),
    collection: 'Twin Set Collection',
    collectionImages: [
      require('../assets/images/lilith/Twin Set/unfazed.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_2.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_3.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_4.jpg'),
      require('../assets/images/lilith/Twin Set/unfazed_5.jpg'),
    ],
    brandLogo: require('../assets/images/lilith/lilith_logo.jpg'),
    isCollectionItem: true,
  },

  // Lilith - Jumpsuit Collection
  {
    id: 'jumpsuit_1',
    name: 'Jumpsuit Collection Item 1',
    brand: 'Lilith',
    price: 4200,
    image: require('../assets/images/lilith/jumpsuit collection/summer.jpg'),
    collection: 'Jumpsuit Collection',
    collectionImages: [
      require('../assets/images/lilith/jumpsuit collection/summer.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_2.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_3.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_4.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_5.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_6.jpg'),
    ],
    brandLogo: require('../assets/images/lilith/lilith_logo.jpg'),
    isCollectionItem: true,
  },

  {
    id: 'jumpsuit_4',
    name: 'Jumpsuit Collection Item 4',
    brand: 'Lilith',
    price: 4200,
    image: require('../assets/images/lilith/jumpsuit collection/summer_4.jpg'),
    collection: 'Jumpsuit Collection',
    collectionImages: [
      require('../assets/images/lilith/jumpsuit collection/summer.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_2.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_3.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_4.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_5.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_6.jpg'),
    ],
    brandLogo: require('../assets/images/lilith/lilith_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'jumpsuit_5',
    name: 'Jumpsuit Collection Item 5',
    brand: 'Lilith',
    price: 4200,
    image: require('../assets/images/lilith/jumpsuit collection/summer_5.jpg'),
    collection: 'Jumpsuit Collection',
    collectionImages: [
      require('../assets/images/lilith/jumpsuit collection/summer.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_2.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_3.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_4.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_5.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_6.jpg'),
    ],
    brandLogo: require('../assets/images/lilith/lilith_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'jumpsuit_6',
    name: 'Jumpsuit Collection Item 6',
    brand: 'Lilith',
    price: 4200,
    image: require('../assets/images/lilith/jumpsuit collection/summer_6.jpg'),
    collection: 'Jumpsuit Collection',
    collectionImages: [
      require('../assets/images/lilith/jumpsuit collection/summer.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_2.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_3.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_4.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_5.jpg'),
      require('../assets/images/lilith/jumpsuit collection/summer_6.jpg'),
    ],
    brandLogo: require('../assets/images/lilith/lilith_logo.jpg'),
    isCollectionItem: true,
  },

  // Est - Casal Green Collection
  {
    id: 'casal_1',
    name: 'Casal Green Item 1',
    brand: 'Est',
    price: 3800,
    image: require('../assets/images/est/casal green/silhouette.jpg'),
    collection: 'Casal Green Collection',
    collectionImages: [
      require('../assets/images/est/casal green/silhouette.jpg'),
      require('../assets/images/est/casal green/silhouette_2.jpg'),
      require('../assets/images/est/casal green/silhouette_3.jpg'),
    ],
    brandLogo: require('../assets/images/est/est_logo.jpg'),
    isCollectionItem: true,
  },
  // Add remaining Casal Green items...

  // Est - Casal Green Collection (continued)
  {
    id: 'casal_2',
    name: 'Casal Green Item 2',
    brand: 'Est',
    price: 3800,
    image: require('../assets/images/est/casal green/silhouette_2.jpg'),
    collection: 'Casal Green Collection',
    collectionImages: [
      require('../assets/images/est/casal green/silhouette.jpg'),
      require('../assets/images/est/casal green/silhouette_2.jpg'),
      require('../assets/images/est/casal green/silhouette_3.jpg'),
    ],
    brandLogo: require('../assets/images/est/est_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'casal_3',
    name: 'Casal Green Item 3',
    brand: 'Est',
    price: 3800,
    image: require('../assets/images/est/casal green/silhouette_3.jpg'),
    collection: 'Casal Green Collection',
    collectionImages: [
      require('../assets/images/est/casal green/silhouette.jpg'),
      require('../assets/images/est/casal green/silhouette_2.jpg'),
      require('../assets/images/est/casal green/silhouette_3.jpg'),
    ],
    brandLogo: require('../assets/images/est/est_logo.jpg'),
    isCollectionItem: true,
  },

  // Anon - Commissioner Collection
  {
    id: 'commissioner_1',
    name: 'Commissioner Item 1',
    brand: 'Anon',
    price: 4500,
    image: require('../assets/images/anon/commissioner/atelier.heic'),
    collection: 'Commissioner Collection',
    collectionImages: [
      require('../assets/images/anon/commissioner/atelier.heic'),
      require('../assets/images/anon/commissioner/atelier_2.heic'),
      require('../assets/images/anon/commissioner/atelier_3.heic'),
      require('../assets/images/anon/commissioner/atelier_4.heic'),
    ],
    brandLogo: require('../assets/images/anon/anon_logo.jpg'),
    isCollectionItem: true,
  },
  // Add remaining Commissioner items...

  // Anon - Commissioner Collection (continued)
  {
    id: 'commissioner_2',
    name: 'Commissioner Item 2',
    brand: 'Anon',
    price: 4500,
    image: require('../assets/images/anon/commissioner/atelier_2.heic'),
    collection: 'Commissioner Collection',
    collectionImages: [
      require('../assets/images/anon/commissioner/atelier.heic'),
      require('../assets/images/anon/commissioner/atelier_2.heic'),
      require('../assets/images/anon/commissioner/atelier_3.heic'),
      require('../assets/images/anon/commissioner/atelier_4.heic'),
    ],
    brandLogo: require('../assets/images/anon/anon_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'commissioner_3',
    name: 'Commissioner Item 3',
    brand: 'Anon',
    price: 4500,
    image: require('../assets/images/anon/commissioner/atelier_3.heic'),
    collection: 'Commissioner Collection',
    collectionImages: [
      require('../assets/images/anon/commissioner/atelier.heic'),
      require('../assets/images/anon/commissioner/atelier_2.heic'),
      require('../assets/images/anon/commissioner/atelier_3.heic'),
      require('../assets/images/anon/commissioner/atelier_4.heic'),
    ],
    brandLogo: require('../assets/images/anon/anon_logo.jpg'),
    isCollectionItem: true,
  },
  {
    id: 'commissioner_4',
    name: 'Commissioner Item 4',
    brand: 'Anon',
    price: 4500,
    image: require('../assets/images/anon/commissioner/atelier_4.heic'),
    collection: 'Commissioner Collection',
    collectionImages: [
      require('../assets/images/anon/commissioner/atelier.heic'),
      require('../assets/images/anon/commissioner/atelier_2.heic'),
      require('../assets/images/anon/commissioner/atelier_3.heic'),
      require('../assets/images/anon/commissioner/atelier_4.heic'),
    ],
    brandLogo: require('../assets/images/anon/anon_logo.jpg'),
    isCollectionItem: true,
  },

  // Standalone Products (No Collection)
  {
    id: 'bo_standalone',
    name: "Bo' Special Edition",
    brand: 'Lilith',
    price: 2800,
    image: require('../assets/images/lilith/Bo`.jpg'),
    brandLogo: require('../assets/images/lilith/lilith_logo.jpg'),
    isCollectionItem: false,
  },
]; 